### ISSUE TITLE
Feature-box is not support for multilingual

### ISSUE THREAD

**Issue by Pisethk** [OpenDevelopmentMekong/wp-feature-box#7]
@acorbi @Huyeng , Please make the code update for multi-language support on wp-feature-box since it is not available for Khmer language. Thanks  

![screenshot_3](https://cloud.githubusercontent.com/assets/10007839/20994990/927f5216-bd26-11e6-8c40-b82b796bb05c.png)

**Comment by acorbi** [comment]
thanks for raising this @Pisethk , @Huyeng has submitted a Pull request already which is being reviewed by @DBishton at the moment. Will deploy the changes soon
